/**
 * Scrabble Parkour — Decentraland Game Jam 2026
 *
 * A 12x12 parcel world split into five 4x4 zones. Four of them (jungle maze,
 * industrial parkour, Egyptian tomb tower, frozen peaks) scatter letter tiles
 * that players race to collect; the fifth is a 21x21 Scrabble board where those
 * tiles get spent on words. Rounds last 10 minutes.
 *
 * All static scenery lives in assets/scene/main.composite (generated by
 * tools/gen-world.mjs). This file only wires up runtime behaviour.
 */

import { engine, SkyboxTime } from '@dcl/sdk/ecs'
import { MessageBus } from '@dcl/sdk/message-bus'
import { SKYBOX_FIXED_TIME } from './generated/layout'
import { createSyncedState } from './state'
import { setupHighlight, setupTileVisuals, syncBoardVisuals, clearBoardVisuals } from './view'
import { setupTileInteractions } from './tiles'
import { setupHost } from './host'
import { setupUi } from './ui'
import { preloadDictionary } from './dictionary'
import { setupPerformance, snapshotDecor } from './perf'
import { quality } from './platform'
import { getRound } from './state'
import { setupSfx } from './sfx'

let lastRenderedRound = -1

export function main(): void {
  // Must run before anything creates a runtime entity, so the snapshot contains
  // only authored scenery.
  snapshotDecor()

  // Pin the sky to noon. scene.json already carries skyboxConfig.fixedTime, but a
  // SkyboxTime component on RootEntity outranks it, so this also covers local
  // preview and any realm that ignores the JSON. Delete it to get the normal
  // day/night cycle back.
  SkyboxTime.createOrReplace(engine.RootEntity, { fixedTime: SKYBOX_FIXED_TIME })

  // syncEntity must never run at module scope — everything synced is built here.
  createSyncedState()

  const bus = new MessageBus()

  setupSfx()
  setupTileVisuals()
  setupHighlight()
  setupTileInteractions(bus)
  setupHost(bus)
  setupUi()
  setupPerformance()

  engine.addSystem(boardRenderSystem)

  // Decode the word list up front so the first placement never stutters.
  preloadDictionary()
}

let accum = 0
function boardRenderSystem(dt: number): void {
  accum += dt
  if (accum < quality().boardInterval) return
  accum = 0

  const round = getRound()
  if (round && round.roundId !== lastRenderedRound) {
    lastRenderedRound = round.roundId
    clearBoardVisuals()
  }
  syncBoardVisuals()
}
